### ISSUE TITLE
Is it possible to view Peripherals in debug mode?

### ISSUE THREAD

**Issue by alpelectronics** [Analog-Devices-MSDK/VSCode-Maxim#10]
Right now, it is like that when I try to debug. Otherwise it is hard to know, if set a register correctly. 

![image](https://user-images.githubusercontent.com/10106458/175821268-ceee3cd5-50cc-4bc5-be68-08893c400b03.png)

**Comment by alpelectronics** [comment]
Thanks Jake, I will try!

**Comment by sullivanmj** [comment]
Awesome tip for viewing register values in the watch window with hex or binary representation!

For others who find this thread, the cortex-debug file does a pretty good job if you point it to the .svd files provided in the Maxim SDK at

MaximSDK/Libraries/CMSIS/Device/Maxim/{your device}/Include/{your device}.svd

**Comment by Jake-Carter** [comment]
> For others who find this thread, the cortex-debug file does a pretty good job if you point it to the .svd files provided in the Maxim SDK at
> 
> MaximSDK/Libraries/CMSIS/Device/Maxim/{your device}/Include/{your device}.svd

Thanks @sullivanmj.  [cortex-debug](https://github.com/Marus/cortex-debug) is a good extension and I'd love to get a similar peripheral browser created.  

I've evaluated it as a replacement for the official [cpptools](https://github.com/Microsoft/vscode-cpptools) debugger configs that I'm currently using, since I'm not really happy with the their config options and the way they drive the [MIEngine](https://github.com/Microsoft/MIEngine).  I'm fighting cpptools a little bit to get it to work for embedded targets, but the setup is functional.  The downside to bringing in cortex-debug is that our micros also include RISC-V cores which would not be covered by the extension.

I've started laying the groundwork for a custom extension with some of my colleagues, and a peripheral browser is definitely on the feature list, among other improvements.  If you have any additional feedback don't hesitate to let me know.

**Comment by sullivanmj** [comment]
A custom peripheral browser would be awesome. Point taken about supporting RISC-V cores, I hadn't considered that since we've only used MCUs with Arm cores.

My team and I really appreciate the work you've done with this repository. None of us really like Eclipse all that much, so it was great to find some help setting up the toolchain and integrating with the SDK from VS Code.

**Comment by Jake-Carter** [comment]
Thanks @sullivanmj, happy to hear it!

**Comment by Jake-Carter** [comment]
Closing this ticket - this info has been copied into the new [wiki](https://github.com/Analog-Devices-MSDK/VSCode-Maxim/wiki/Peripheral-Browsing)
