### ISSUE TITLE
Flashing Error with MAX78000 FTHR RevA not finding `interface/cmsis-dap.cfg`

### ISSUE THREAD

**Issue by d-mironov** [Analog-Devices-MSDK/VSCode-Maxim#19]
**Visual Studio Code version**
- 1.80.2

**C/C++ Extension version**
- 1.16.3

**Target microcontroller and evaluation platform**
- MAX78000 FTHR RevA

**Describe the bug**
When I copy the `Hello_World` example and try to flash it, it compiles just fine but fails to upload with the following error message.
```
 *  Executing task: arm-none-eabi-gdb --cd="C:\Users\Athri\Documents\Development\Embedded\MAX78000\template-cpp" --se="build/template-cpp.elf" --symbols=build/template-cpp.elf -x="C:\Users\Athri\Documents\Development\Embedded\MAX78000\template-cpp/.vscode/flash.gdb" --ex="flash_m4_run C:\MaximSDK/Tools/OpenOCD cmsis-dap.cfg max78000.cfg" --batch 

C:\MaximSDK\Tools\GNUTools\10.3\bin\arm-none-eabi-gdb.exe: warning: Couldn't determine a path for the index cache directory.
The target architecture is set to "armv7e-m".
Open On-Chip Debugger 0.11.0+dev-g56a818e4c (2023-06-28-22:13)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Remote communication error.  Target disconnected.: No error.
```
The `flash.log` file contains the following:
```
embedded:startup.tcl:26: Error: Can't find interface/cmsis-dap.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 26
```

So it's some kind of issue with Windows 11 and the file path of the OpenOCD interface file. 

**What I've tried:**
- Reinstalling the MaximSDK
- Changing all the paths in the `.json` files from `/` to `\\` because Windows. ^^

**To Reproduce**
1. Copy `Hello_World` folder
2. Open with VSCode
3. Hit Ctrl+Shift+B and select `flash & run`

**Screenshots**
- If applicable, add screenshots to help explain your problem.

**Desktop:**
 - OS: Windows 11

**Comment by d-mironov** [comment]
Fixed it. It was a weird Path thing with windows to use `/` instead of `\`.

**Comment by d-mironov** [comment]
So I managed to fix the issue noted in the `flash.log`. But I still get another error when flashing:
```
DEPRECATED! use 'adapter driver' not 'interface'
Info : CMSIS-DAP: SWD  supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: Test domain timer supported
Info : CMSIS-DAP: FW Version = 0256
Info : CMSIS-DAP: Serial# = 044417015f1108ae00000000000000000000000097969906
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Info : SWD DPIDR 0x2ba01477
Info : max32xxx.cpu: Cortex-M4 r0p1 processor detected
Info : max32xxx.cpu: target has 6 breakpoints, 4 watchpoints
Error: max32xxx.cpu -- clearing lockup after double fault
Info : max32xxx.cpu: external reset detected
Info : starting gdb server for max32xxx.cpu on pipe
Info : SWD DPIDR 0x2ba01477
target halted due to debug-request, current mode: Thread 
xPSR: 0x81000000 pc: 0x00002124 msp: 0x20003ff0
Error: couldn't bind tcl to socket on port 6666: No error
```

**Comment by d-mironov** [comment]
Okay.
So basically in Windows this is caused by some Process using port `6666`. From a StackOverflow post I tried the commands:
```
$portProcessID = ( Get-NetTCPConnection -LocalPort 6666 ).OwningProcess
( Get-WmiObject win32_process | Where-Object {$_.ProcessID -eq $portProcessID } ).ProcessName
Stop-Process -id $portProcessID
```
to kill the process and now the flashing works.

**Comment by Jake-Carter** [comment]
Hi @d-mironov sorry for the delay on this, I just saw you closed it so it got pushed to the bottom of my stack.

For the first flashing error I suspect `"MAXIM_PATH":"C:\\MaximSDK"` was the problem.  Backslashes will break the flashing script on Windows, which is why we recommend in the [setup procedure](https://analog-devices-msdk.github.io/msdk/USERGUIDE/#setup-vs-code) to use forward slashes.  Can you confirm?

The second issue with the port 6666 conflict is more strange.  I've never seen anything occupy that on system startup before.  What was the exact process name in your case?  FWIW the tcl port is unused by default, but OpenOCD does attempt to open it.

**Comment by d-mironov** [comment]
No worries. Thanks for taking the time.

Yes the first problem was caused by using backslashes for the `MAXIM_PATH`. Just thought it's necessary, because ... Windows. I guess I'll switch back to Linux ^^

For the port problem I can check the process when I come back home tomorrow and report back to you.

**Comment by Jake-Carter** [comment]
Yep Windows backslashes are frequently the bane of my existence.

FYI since you're on W11 our Ubuntu installer will work inside WSL2.  I use WSL2 and VS Code's [WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) as my primary dev environment.  USB passthrough is the most difficult thing to set up, but [ubsipd-win](https://github.com/dorssel/usbipd-win) has gotten pretty good/stable.

Instructions aren't in the MSDK UG yet because I found I had to modify the WSL2 kernel to enable the HIDRAW module.  I threw it up the kernel binary on my personal Github [here](https://github.com/Jake-Carter/WSL2-Linux-Kernel/releases/tag/v5.15.90.1-hidraw) (which is in no way associated with ADI).

Getting the USB passthrough working can take some troubleshooting, but if you go down that route it's worth it to get the debugger and serial ports working semi-natively.

> For the port problem I can check the process when I come back home tomorrow and report back to you.

Thanks.  Just want to see if we need to handle this conflict on our side

**Comment by d-mironov** [comment]
Alright. I've looked into USB passthrough with WSL2 but had no time setting it up. Need to look into it further.

The Process which had problems with the port is called: `AgentService.exe`
And some googling around this is no Windows service, so there is something on my computer with the service started and using port `6666`.

**Comment by Jake-Carter** [comment]
Thanks.  Since it's not a built-in Windows app we'll leave the default port as-is.  For your system I would suggest editing the `Tools/OpenOCD/scripts/interface/cmsis-dap.cfg` file.

You can add your "tcl_port 10124" line to that file to change the port for all your debug sessions, so that way you don't need to edit flash.gdb for each project.

**Comment by d-mironov** [comment]
Yeah thats what I already suggested in one of my comments. With it it works perfectly fine
